// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz2p_DT1mvCt_rlcdsPJaPtXigMbXMBf0',
    appId: '1:433655407130:web:46ea22eaa6dc3bb324a7a3',
    messagingSenderId: '433655407130',
    projectId: 'fir-84f9b',
    authDomain: 'fir-84f9b.firebaseapp.com',
    databaseURL: 'https://fir-84f9b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-84f9b.appspot.com',
    measurementId: 'G-5R530RB4Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC80-TRoDq0hA8ZNXTfwqMCKf76pI1b7ag',
    appId: '1:433655407130:android:5d7d2241b1264f8f24a7a3',
    messagingSenderId: '433655407130',
    projectId: 'fir-84f9b',
    databaseURL: 'https://fir-84f9b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-84f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Bo3BLHLDCB517USJhJ1AB9TbH8etl48',
    appId: '1:433655407130:ios:58f83e3cca7106ac24a7a3',
    messagingSenderId: '433655407130',
    projectId: 'fir-84f9b',
    databaseURL: 'https://fir-84f9b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-84f9b.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Bo3BLHLDCB517USJhJ1AB9TbH8etl48',
    appId: '1:433655407130:ios:eb1b9656082aea8224a7a3',
    messagingSenderId: '433655407130',
    projectId: 'fir-84f9b',
    databaseURL: 'https://fir-84f9b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-84f9b.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
